---
- hosts: all
  become: yes
  tasks:
  - name: "Update repositories cache"
    apt:
      update_cache: yes

  - name: "Installing handy tools via package manager"
    ignore_errors: 'yes'
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - fish
      - python3
      - python3-pip
      - git
      - terminator
      # - alacarte
      - htop
      - virtualbox-guest-x11
      - exiftool
      - rpcbind
      - rinetd
      - jq
      - awscli
      - sharutils
      - keepass2
      - docker
      - libreoffice
      - npm

  - name: "Installing Python3 Packages"
    shell: pip3 install pyinstaller pipreqs truffleHog r3con1z3r pwncat

  #- name: "Enable Docker service, enable on startup, allow non-root user to run"
  #  shell: "sudo systemctl start docker"
  #  shell: "sudo systemctl enable docker"
  #  shell: "sudo usermod -aG docker $USER"

  # ==========================================================#
  # Nmap Scripts:
  # ==========================================================#
  - name: "Download nmap banner-plus.nse"
    get_url:
      url: https://raw.githubusercontent.com/grimmvenom/infosec/master/nmap_nse_scripts/banner-plus.nse
      dest: /usr/share/nmap/scripts/banner-plus.nse
      # mode: '0440'

  - name: "Download nmap ms15-034.nse"
    get_url:
      url: https://raw.githubusercontent.com/grimmvenom/infosec/master/nmap_nse_scripts/ms15-034.nse
      dest: /usr/share/nmap/scripts/ms15-034.nse
      # mode: '0440'

  - name: "Download nmap vmware-fingerprint.nse"
    get_url:
      url: https://raw.githubusercontent.com/grimmvenom/infosec/master/nmap_nse_scripts/vmware-fingerprint.nse
      dest: /usr/share/nmap/scripts/vmware-fingerprint.nse
      # mode: '0440'

  - name: "Download nmap http-screenshot-html.nse"
    get_url:
      url: https://raw.githubusercontent.com/grimmvenom/infosec/master/nmap_nse_scripts/http-screenshot-html.nse
      dest: /usr/share/nmap/scripts/http-screenshot-html.nse
      # mode: '0440'

  # ==========================================================#
  # Documentation:
  # ==========================================================#

  - name: "Make OWASP directory"
    file:
     path: /home/vagrant/Documents/owasp
     state: directory
     mode: 0755
     group: vagrant
     owner: vagrant
    # when: stat_result.stat.exists == false

  # Download OWASP ASVS Documentation:
  - name: "Download ASVS Documentation"
    git:
      repo: https://github.com/OWASP/ASVS
      dest: /home/vagrant/Documents/owasp/owasp-ASVS

  # Download OWASP MASVS
  - name: "Download OWASP MASVS"
    git:
      repo: https://github.com/OWASP/owasp-masvs
      dest: /home/vagrant/Documents/owasp/owasp-masvs

  # Download OWASP Mobile Security Testing Guide
  - name: "Download OWASP Mobiule Security Testing Guide"
    git:
      repo: https://github.com/OWASP/owasp-mstg
      dest: /home/vagrant/Documents/owasp/owasp-mstg

  # Download Cheatsheets / Notes:
  - name: "Download Awesome-Pentest-Cheat-Sheets"
    git:
      repo:  https://github.com/coreb1t/awesome-pentest-cheat-sheets
      dest: /home/vagrant/Documents/cheatsheets/

  # Download Wordlists
  - name: "Download SecLists Wordlists"
    git:
      repo: https://github.com/danielmiessler/SecLists
      dest: /usr/share/wordlists/SecLists

  - name: "Download Awesome-Fuzzing Wordlists"
    git:
      repo:  https://github.com/secfigo/Awesome-Fuzzing
      dest: /usr/share/wordlists/Awesome-Fuzzing

  - name: "Download Awesome-Hacking Wordlists"
    git:
      repo: https://github.com/Hack-with-Github/Awesome-Hacking
      dest: /usr/share/wordlists/Awesome-Hacking

  # ==========================================================#
  # Recon / Enumeration Tools:
  # ==========================================================#

  # Arachni Scanner:  https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz

  - name: "Download GoWitness: https://github.com/sensepost/gowitness"
    git:
      repo: https://github.com/sensepost/gowitness.git
      dest: /opt/goWitness

  - name: "Download WhatWeb:  https://github.com/urbanadventurer/WhatWeb.git"
    git:
      repo: https://github.com/urbanadventurer/WhatWeb
      dest: /opt/WhatWeb

  - name: "Download Responder: https://github.com/lgandx/Responder.git"
    git:
      repo: https://github.com/lgandx/Responder
      dest: /opt/Responder

  - name: "Discover: https://github.com/leebaird/discover"
    git:
      repo: https://github.com/leebaird/discover
      dest: /opt/Discover

  - name: "Download Sublist3r: https://github.com/aboul3la/Sublist3r"
    git:
      repo: https://github.com/aboul3la/Sublist3r.git
      dest: /opt/Sublist3r

  - name: "Download Amass: https://github.com/OWASP/Amass"
    git:
      repo: https://github.com/OWASP/Amass
      dest: /opt/amass

  - name: "Th3Inspecter: https://github.com/Moham3dRiahi/Th3inspector"
    git:
      repo: https://github.com/Moham3dRiahi/Th3inspector
      dest: /opt/Th3Inspecter

  - name: "Download Photon: https://github.com/s0md3v/Photon"
    git:
      repo: https://github.com/s0md3v/Photon
      dest: /opt/Photon

  - name: "Download DNSRecon: https://github.com/darkoperator/dnsrecon"
    git:
      repo: https://github.com/darkoperator/dnsrecon
      dest: /opt/dnsrecon

  - name: "Download Impacket: https://github.com/CoreSecurity/impacket.git"
    git:
      repo: https://github.com/CoreSecurity/impacket
      dest: /opt/impacket

  - name: "Download BloodHound: https://github.com/BloodHoundAD/BloodHound"
    git:
      repo: https://github.com/BloodHoundAD/BloodHound
      dest: /opt/BloodHound

  - name: "Download RedTeam Scripts: https://github.com/threatexpress/red-team-scripts"
    git:
      repo: https://github.com/threatexpress/red-team-scripts
      dest: /opt/RedTeamScripts

  # ==========================================================#
  # Powershell Exploit via Kali:
  # ==========================================================#
  - name: "Download PSEmpire: https://github.com/EmpireProject/Empire"
    git:
      repo: https://github.com/EmpireProject/Empire
      dest: /opt/PowerShell/Empire

  #- name: "Download PowerSploit: https://github.com/PowerShellMafia/PowerSploit/"
  #  git:
  #    repo: https://github.com/PowerShellMafia/PowerSploit
  #    dest: /opt/PowerShell/PowerSploit

  - name: "Download PS DeathStar: https://github.com/byt3bl33d3r/DeathStar"
    git:
      repo: https://github.com/byt3bl33d3r/DeathStar
      dest: /opt/PowerShell/DeathStar


  # ==========================================================#
  #  Mobile Pentesting Tools
  # ==========================================================#

  - name: "Installing PassionFruit: https://github.com/chaitin/passionfruit"
    shell: "npm install -g passionfruit"

  # Install ADB Platform Tools for android
  # https://developer.android.com/studio/releases/platform-tools

  - name: "Installing Frida"
    shell: pip3 install frida-tools frida

  - name: "Download MobSF: https://github.com/MobSF/Mobile-Security-Framework-MobSF"
    git:
      repo: https://github.com/MobSF/Mobile-Security-Framework-MobSF
      dest: /opt/mobile/mobsf
